language: node_js
node_js:
  - "0.12"
services:
  - mongodb
env:
  global:
    - UI=ui
    - API=service
before_install:
  - npm config set spin false
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - cd $UI
  - npm install
  - bower install
  - cd ..
  - cd $API
  - npm install
  - cd ..
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm test
